name: Sync labels

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  issues: write

jobs:
  call-workflow:
    uses: otaku-melons/.github/.github/workflows/sync-labels.yml@main
